# Generated by Django 2.2.4 on 2019-10-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_sent',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
