# Generated by Django 2.2.4 on 2019-10-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='attachment_name',
        ),
        migrations.AlterField(
            model_name='chat',
            name='attachment',
            field=models.ImageField(upload_to='images/attachment/'),
        ),
    ]
